### ISSUE TITLE
no glow on saber highlights

### ISSUE THREAD

**Issue by dmarcos** [supermedium/supersaber#229]
![glow](https://d3vv6lp55qjaqc.cloudfront.net/items/3z0n031A0L290W1N2d0c/Image%202018-12-10%20at%201.57.35%20PM.png?X-CloudApp-Visitor-Id=222920&v=445c5d3e)

**Comment by ngokevin** [comment]
https://github.com/supermedium/supersaber/commit/f03bebd3a8a79e90345cd049250630af1202b08f
