### ISSUE TITLE
Incorrect selection highlighting 

### ISSUE THREAD

**Issue by dmarcos** [supermedium/supersaber#230]
Clicking on the `normal` difficulty level selects it properly but highlight does not reflect the selection

![highlight](https://user-images.githubusercontent.com/39342/49765202-96c35100-fc86-11e8-9fbc-cc5fec0ed12a.gif)

**Comment by ngokevin** [comment]
https://github.com/supermedium/supersaber/commit/84f93a48d376445b889ced86db2675b30848ee3a
